import json
from typing import List, Dict, Any
import google.generativeai as genai
import os

# Configure Gemini
if os.getenv("GEMINI_API_KEY"):
    genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

def generate_video_metadata(transcript: List[Dict], is_short: bool = False) -> Dict[str, Any]:
    """
    Generates YouTube metadata (title, description, tags) from the transcript using Gemini.
    """
    try:
        text_content = " ".join([t['text'] for t in transcript])
        
        prompt = f"""
        Analyze the following video transcript and generate YouTube metadata.
        
        Transcript:
        {text_content[:2000]}... (truncated)

        Requirements:
        1. Title: Catchy, click-baity but relevant. Max 100 chars. {'Include #Shorts if is_short' if is_short else ''}
        2. Description: Summary of the content, key points. Max 500 chars.
        3. Tags: 10-15 relevant keywords, comma separated.
        4. Category ID: Suggest a YouTube category ID (e.g., 22 for People & Blogs, 24 for Entertainment). Default to 22.

        Output JSON format:
        {{
            "title": "...",
            "description": "...",
            "tags": ["tag1", "tag2"],
            "categoryId": "22"
        }}
        """

        model = genai.GenerativeModel('gemini-2.0-flash-exp')
        response = model.generate_content(prompt)
        
        # Clean up response
        text = response.text.strip()
        if text.startswith("```json"):
            text = text[7:-3]
        
        data = json.loads(text)
        
        # Fallback/Validation
        if not data.get('title'): data['title'] = "Auto-Clipped Video"
        if not data.get('description'): data['description'] = "Generated by Auto-Clipper"
        if not data.get('tags'): data['tags'] = ["AutoClipper", "AI"]
        if not data.get('categoryId'): data['categoryId'] = "22"
        
        return data

    except Exception as e:
        print(f"Metadata generation failed: {e}")
        return {
            "title": "Auto-Clipped Video",
            "description": "Generated by Auto-Clipper",
            "tags": ["AutoClipper", "AI"],
            "categoryId": "22"
        }
